language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      env: TOXENV=py27
      install: pip install tox codecov
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      env: TOXENV=py37
      install: pip3 install tox codecov
#    - name: "Python 3.7.4 on macOS"
#      os: osx
#      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=py37
      install: pip3 install tox codecov

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
